# Generated by Django 2.1.5 on 2023-05-16 12:23

import colorful.fields
import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60)),
                ('home_box_image', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('home_box_text', models.CharField(blank=True, max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('content_title_top', models.CharField(blank=True, max_length=200, verbose_name='Title Top')),
                ('content_text_top', models.TextField(blank=True, verbose_name='Text Top')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterColumn1Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='Or URL')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Footer Column 1 Item',
                'verbose_name_plural': 'Footer Column 1 Items',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterColumn2Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='Or URL')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Footer Column 2 Item',
                'verbose_name_plural': 'Footer Column 2 Items',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_color_sides', colorful.fields.RGBColorField(default='#01123e')),
                ('header_color_center', colorful.fields.RGBColorField(default='#306da3')),
            ],
            options={
                'verbose_name': 'Header',
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='Or URL')),
                ('delay', models.IntegerField(default=3, help_text='In seconds')),
            ],
            options={
                'verbose_name': 'Popup',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=70, verbose_name='SKU')),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Regular price')),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sale price')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popular')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='On sale')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='Coming soon')),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_popular', '-created_date'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.helpers.upload_product_images_to)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=200)),
                ('footer_scripts', models.TextField(blank=True, help_text="Don't forget to wrap code in &lt;script&gt; tag")),
                ('email_list', models.TextField(blank=True, help_text='One email per line')),
                ('vanities_link', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=100)),
                ('contact_address', models.TextField(blank=True)),
                ('working_hours', models.TextField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('google_plus_link', models.URLField(blank=True)),
                ('houzz_link', models.URLField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='TopNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='Or URL')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Navigation Item',
            },
        ),
    ]
