# Generated by Django 2.1.5 on 2023-05-16 12:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnavigationitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page'),
        ),
        migrations.AddField(
            model_name='topnavigationitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.TopNavigationItem'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeManyToManyField(related_name='products', to='core.Category'),
        ),
        migrations.AddField(
            model_name='popup',
            name='button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page'),
        ),
        migrations.AddField(
            model_name='footercolumn2item',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Footer'),
        ),
        migrations.AddField(
            model_name='footercolumn2item',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
        migrations.AddField(
            model_name='footercolumn1item',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Footer'),
        ),
        migrations.AddField(
            model_name='footercolumn1item',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='topnavigationitem',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
    ]
