# Generated by Django 2.1.5 on 2023-05-16 12:23

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.helpers.upload_gallery_images_to)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.helpers.upload_common_images_to)),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('subheader', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='Or URL')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('is_category_submenu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pages.Page')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('banner_text', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('content', redactor.fields.RedactorField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pages.Page')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('banner_text', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', redactor.fields.RedactorField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('content', redactor.fields.RedactorField(blank=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pages.Page')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('banner_text', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Gallery Page',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pages.Page')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_heading', models.CharField(blank=True, max_length=200)),
                ('video_description', models.TextField(blank=True)),
                ('video_embed_url', models.URLField(blank=True)),
                ('featured_products', models.ManyToManyField(blank=True, to='core.Product')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='OnSalePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pages.Page')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('banner_text', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'On Sale Page',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='ReviewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pages.Page')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_common_images_to)),
                ('banner_text', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Reviews Page',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='TourPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pages.Page')),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.CharField(default='TOUR OUR STORE', max_length=100)),
                ('video_tour_url', models.URLField(blank=True)),
                ('virtual_tour_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Tour Page',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.ReviewsPage'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='home_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='pages.HomePage'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='gallery_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.GalleryPage'),
        ),
    ]
